name: windows-test

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - 'dependabot*'

jobs:

  dev:

    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "CONDA_ENV_FILE=ci/requirements/py3.8-free-small.yml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=3.8" >> $GITHUB_ENV

      - name: Cache conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-py3.8-${{ hashFiles('ci/requirements/**.yml') }}

      - name: Set up environment with py-3.8
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          channel-priority: strict
          mamba-version: "*"
          activate-environment: argopy-tests
          python-version: 3.8
          auto-update-conda: false
          use-only-tar-bz2: true

      - name: Install conda dependencies
        run: |
          mamba env update -f $CONDA_ENV_FILE

      - shell: bash -l {0}
        run: |
          conda info
          conda list

      - shell: bash -l {0}
        run: |
          python -c "import fsspec; print(fsspec.__version__, ':', fsspec.filesystem('file').sep)"
